Stop tracking metrics, because dvc told me to
> python evaluate.py --stage_name evaluate_fit_train
gender default
occupation default
activity default
default default
Target column, not a feature. Skipping.
ERROR: failed to reproduce 'evaluate_fit_train':  output '../../notebooks/data/evaluate_fit_train' is already tracked by SCM (e.g. Git).
    You can remove it from Git, then add to DVC.
        To stop tracking from Git:
            git rm -r --cached '../../notebooks/data/evaluate_fit_train'
            git commit -m "stop tracking ../../notebooks/data/evaluate_fit_train"